name: 'CI'
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v1.1.1
        with:
          versionSpec: '5.x'

      - name: Determine Version
        id: version_step # step id used as reference for output values
        uses: gittools/actions/gitversion/execute@v1.1.1

      - run: dotnet restore               # install packages
      - run: dotnet build -c Release --no-restore    # build
      - run: 'dotnet test -c Release --no-build --verbosity normal --filter TestCategory!=EOR --logger "trx;LogFileName=test-results.trx"' # run tests
      - run: 'cp "${{ github.workspace }}/ACDatReader.Tests/TestResults/test-results.trx" "${{ github.workspace }}/test-results.xml" '
      - uses: actions/upload-artifact@v3  # upload test results
        if: success() || failure()        # run this step even if previous step failed
        with:
          name: test-results
          path: 'test-results.xml'

      - run: dotnet pack -c Release
      - run: dotnet nuget add source --username USERNAME --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/ACClientLib/index.json"
  
      - run: dotnet nuget push "${{ github.workspace }}/ACDatReader/bin/Release/net8.0/ACClientLib.DatReader.${{ env.GitVersion_FullSemVer }}.nupkg" --source "github"